stages:
  - build
  - deploy

variables:
  POSTGRES_USER: "your_postgres_user"
  POSTGRES_PASSWORD: "your_postgres_password"
  POSTGRES_DB: "your_postgres_db"
  DB_HOST: "database"
  DB_PORT: 5432
  DB_USER: "your_db_user"
  DB_PASS: "your_db_password"
  DB_NAME: "your_db_name"
  CLEARML_API_HOST: "your_clearml_api_host"
  CLEARML_WEB_HOST: "your_clearml_web_host"
  CLEARML_FILES_HOST: "your_clearml_files_host"
  CLEARML_ACCESS_KEY: "your_clearml_access_key"
  CLEARML_SECRET_KEY: "your_clearml_secret_key"
  RABBITMQ_DEFAULT_USER: "your_rabbitmq_user"
  RABBITMQ_DEFAULT_PASS: "your_rabbitmq_password"

services:
  - docker:docker:27.3.1

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying your application..."
  only:
    - main