stages:
  - build
  - deploy

variables:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "sample_db"
  DB_HOST: "database"
  DB_PORT: 5432
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_NAME: "sample_db"
  CLEARML_API_HOST: "https://api.clear.ml"
  CLEARML_WEB_HOST: "https://app.clear.ml"
  CLEARML_FILES_HOST: "https://files.clear.ml"
  CLEARML_ACCESS_KEY: "E15TPK6JGIWCCDBJ58ZHPRUO29MFWM"
  CLEARML_SECRET_KEY: "mfFbvwqCg2of2VUZqfqkvEqS2M2Y6fqIwYoBDmu8wPBegQ_0NDx3cn_mY9gn9kXU-do"
services:
  - docker:docker:27.3.1

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying your application..."
  only:
    - main