services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sample_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    environment:
      - CLEARML_API_HOST=${CLEARML_API_HOST}
      - CLEARML_WEB_HOST=${CLEARML_WEB_HOST}
      - CLEARML_FILES_HOST=${CLEARML_FILES_HOST}
      - CLEARML_ACCESS_KEY=${CLEARML_ACCESS_KEY}
      - CLEARML_SECRET_KEY=${CLEARML_SECRET_KEY}
    depends_on:
      database:
        condition: service_healthy

  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - database

volumes:
  postgres_data:



 # streamlit:
  #   build: ./streamlit
  #   ports:
  #     - 8888:8501
  #   volumes:
  #     - ./streamlit:/streamlit
  #   depends_on:
  #     - app
